/**
 * Generates src/preflop-table.ts: every starting hand's all-in equity against one random hand, by a
 * seeded simulation (ties count half). Deterministic: the same seed gives the same table.
 *
 *   pnpm tsx packages/engine/scripts/preflop-table.ts [samples per hand, default 100000]
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fullDeck, RANKS, type Card } from '../src/cards'
import { evaluateHand } from '../src/evaluate'
import { deriveSeed, mulberry32 } from '../src/rng'

const samples = Number(process.argv[2] ?? 100_000)
const hi = [...RANKS].reverse()

/** The 169 classes, strongest-looking first: pairs on the diagonal, suited above it, offsuit below. */
function classes(): Array<{ hand: string; cards: [Card, Card] }> {
  const out: Array<{ hand: string; cards: [Card, Card] }> = []
  for (let i = 0; i < hi.length; i++)
    for (let j = i; j < hi.length; j++) {
      const a = hi[i]!
      const b = hi[j]!
      if (i === j) out.push({ hand: `${a}${a}`, cards: [`${a}h`, `${a}d`] })
      else {
        out.push({ hand: `${a}${b}s`, cards: [`${a}h`, `${b}h`] })
        out.push({ hand: `${a}${b}o`, cards: [`${a}h`, `${b}d`] })
      }
    }
  return out
}

function equity(cards: [Card, Card], seed: number): number {
  const rest = fullDeck().filter((c) => c !== cards[0] && c !== cards[1])
  const rand = mulberry32(seed)
  let score = 0
  for (let s = 0; s < samples; s++) {
    // A partial Fisher-Yates: the first 7 of the shuffled rest are the opponent's two and the board.
    for (let i = 0; i < 7; i++) {
      const j = i + Math.floor(rand() * (rest.length - i))
      const t = rest[i]!
      rest[i] = rest[j]!
      rest[j] = t
    }
    const board = rest.slice(2, 7)
    const me = evaluateHand([...cards, ...board]).value
    const them = evaluateHand([rest[0]!, rest[1]!, ...board]).value
    score += me < them ? 1 : me === them ? 0.5 : 0
  }
  return score / samples
}

const table = classes().map(({ hand, cards }) => [hand, Math.round(equity(cards, deriveSeed('preflop-table', hand)) * 10_000) / 10_000] as const)
const body = table.map(([hand, eq]) => `  ${/^\d/.test(hand) ? `'${hand}'` : hand}: ${eq},`).join('\n')
const file = `// Generated by scripts/preflop-table.ts (${samples.toLocaleString('en-US')} seeded samples per hand): do not edit.
/**
 * Every starting hand's all-in equity against one random hand, ties counted half. Keys: a pair ("AA"),
 * or two ranks high first with "s" (suited) or "o" (offsuit).
 */
export const PREFLOP_EQUITY: Record<string, number> = {
${body}
}
`
writeFileSync(join(import.meta.dirname, '../src/preflop-table.ts'), file)
console.log(`wrote ${table.length} hands`)
